module.exports = {
    Client: require("./Client"), TransferResponse: require("./responses/TransferResponse"),
    Economy: require("./Economy"), ExchangeClient: require("./exchange/ExchangeClient"),
    ApiRequest: require("./ApiRequest"), ExchangeSettings: require("./exchange/objects/ExchangeSettings"),
    User: require("./Structures/User"), ExchangePool: require("./exchange/objects/ExchangePool"),
    UserBalances: require("./Structures/UserBalances"), ExchangeRates: require("./exchange/objects/ExchangeRates"),
    Change: require("./Structures/Change"), ExchangeHistory: require("./exchange/objects/ExchangeHistory"),
    Transfer: require("./Structures/Transfer"), ExchangeChange: require("./exchange/objects/ExchangeChange"),
    TopUser: require("./Structures/TopUser"), ItemsResponse: require("./responses/ItemsResponse"),
    ChatClient: require("./chat/ChatClient"), ListResponse: require("./responses/ListResponse"),
    ChatAttachment: require("./chat/Structures/ChatAttachment"), Auction: require("./Auction"),
    ChatMessage: require("./chat/Structures/ChatMessage"), AuctionDuration: require("./Structures/AuctionDuration"),
    ChatUser: require("./chat/Structures/ChatUser"), Item: require("./Structures/Item"),
    ChatAttachmentMeta: require("./chat/Structures/ChatAttachmentMeta"), Mod: require("./Structures/Mod"),
    ChatAttachmentType: require("./chat/Structures/ChatAttachmentType"), Buyer: require("./Structures/Buyer"),
    ChatExternalUser: require("./chat/Structures/ChatExternalUser"), ShopDuration: require("./Structures/ShopDuration"),
    ChatSticker: require("./chat/Structures/ChatSticker"), AuctionItem: require("./Structures/AuctionItem"),
    ChatStickerMetadata: require("./chat/Structures/ChatStickerMetadata"), Bid: require("./Structures/Bid"),
    Rank: require("./Structures/Rank"), SellFee: require("./Structures/SellFee"), Stats: require("./Structures/Stats"),
    GetTokenResponse: require("./responses/GetTokenResponse"), Notification: require("./Structures/Notification"),
    ChangesResponse: require("./responses/ChangesResponse"), UserInfoResponse: require("./responses/UserInfoResponse"),
    BalanceResponse: require("./responses/BalanceResponse"), UserSkin: require("./Structures/UserSkin"),
    TransfersResponse: require("./responses/TransfersResponse"), Transaction: require("./Structures/Transaction"),
    TransfersCountResponse: require("./responses/TransfersCountResponse"),
    ChangesCountResponse: require("./responses/ChangesCountResponse"), InvitedUser: require("./Structures/InvitedUser"),
    TopResponse: require("./responses/TopResponse"), UserNotifications: require("./Structures/UserNotifications"),
    TransactionsResponse: require("./responses/TransactionsResponse"),
}